import { useEffect, useState } from 'react';
import { AlertTriangle } from 'lucide-react';
import Hero from './components/Hero';
import EventFeed from './components/EventFeed';
import Sources from './components/Sources';
import Footer from './components/Footer';
import type { EventsPayload } from './types/hackathon';

/**
 * events.json is a static asset regenerated by CI, so this is a plain fetch --
 * no server, no keys, no runtime cost. Netlify serves it from the CDN edge.
 */
function App() {
  const [data, setData] = useState<EventsPayload | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    fetch(`${import.meta.env.BASE_URL}events.json`)
      .then((res) => {
        if (!res.ok) throw new Error(`Could not load events (${res.status})`);
        return res.json() as Promise<EventsPayload>;
      })
      .then((payload) => {
        if (!cancelled) setData(payload);
      })
      .catch((err: Error) => {
        if (!cancelled) setError(err.message);
      });

    return () => { cancelled = true; };
  }, []);

  if (error) {
    return (
      <main className="flex min-h-screen items-center justify-center px-4">
        <div className="card-surface max-w-md p-8 text-center">
          <AlertTriangle className="mx-auto mb-4 h-8 w-8 text-amber-400" aria-hidden="true" />
          <h1 className="mb-2 text-lg font-semibold text-white">Couldn't load the feed</h1>
          <p className="text-sm text-slate-400">{error}</p>
        </div>
      </main>
    );
  }

  if (!data) return <LoadingState />;

  return (
    <div className="min-h-screen">
      <Hero data={data} />
      <main>
        <EventFeed events={data.events} />
        <Sources sources={data.sources} />
      </main>
      <Footer generatedAt={data.generatedAt} />
    </div>
  );
}

/** Skeleton matching the real layout, so there's no jarring reflow. */
function LoadingState() {
  return (
    <div className="mx-auto max-w-7xl animate-pulse px-4 py-24 sm:px-6" aria-busy="true">
      <span className="sr-only">Loading hackathons…</span>
      <div className="h-4 w-48 rounded bg-ink-800" />
      <div className="mt-6 h-14 w-full max-w-2xl rounded bg-ink-800" />
      <div className="mt-4 h-14 w-full max-w-xl rounded bg-ink-800" />
      <div className="mt-16 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {Array.from({ length: 6 }).map((_, i) => (
          <div key={i} className="h-52 rounded-xl bg-ink-850" />
        ))}
      </div>
    </div>
  );
}

export default App;
